CREATE TABLE `Post` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`Content` VARCHAR(255) NOT NULL,
	`UserId` INT NOT NULL,
	PRIMARY KEY (`Id`)
);

CREATE TABLE `Image` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`Path` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`Id`)
);

CREATE TABLE `Role` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`Id`)
);

CREATE TABLE `User` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`Nickname` VARCHAR(255) NOT NULL UNIQUE,
	`Bio` VARCHAR(255) NOT NULL,
	`RoleId` INT NOT NULL,
	PRIMARY KEY (`Id`)
);

CREATE TABLE `PostImage` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`PostId` INT NOT NULL AUTO_INCREMENT,
	`ImageId` INT NOT NULL,
	`ImageNumber` INT NOT NULL,
	PRIMARY KEY (`Id`)
);

CREATE TABLE `UserCredentials` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`Login` VARCHAR(255) NOT NULL UNIQUE,
	`Password` VARCHAR(255) NOT NULL,
	`UserId` INT NOT NULL,
	PRIMARY KEY (`Id`)
);

CREATE TABLE `Tag` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (`Id`)
);

CREATE TABLE `PostTag` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`PostId` INT NOT NULL,
	`TagId` INT NOT NULL,
	PRIMARY KEY (`Id`)
);

ALTER TABLE `Post` ADD CONSTRAINT `Post_fk0` FOREIGN KEY (`UserId`) REFERENCES `User`(`Id`);

ALTER TABLE `User` ADD CONSTRAINT `User_fk0` FOREIGN KEY (`RoleId`) REFERENCES `Role`(`Id`);

ALTER TABLE `PostImage` ADD CONSTRAINT `PostImage_fk0` FOREIGN KEY (`PostId`) REFERENCES `Post`(`Id`);

ALTER TABLE `PostImage` ADD CONSTRAINT `PostImage_fk1` FOREIGN KEY (`ImageId`) REFERENCES `Image`(`Id`);

ALTER TABLE `UserCredentials` ADD CONSTRAINT `UserCredentials_fk0` FOREIGN KEY (`UserId`) REFERENCES `User`(`Id`);

ALTER TABLE `PostTag` ADD CONSTRAINT `PostTag_fk0` FOREIGN KEY (`PostId`) REFERENCES `Post`(`Id`);

ALTER TABLE `PostTag` ADD CONSTRAINT `PostTag_fk1` FOREIGN KEY (`TagId`) REFERENCES `Tag`(`Id`);

